apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: helloworld-task
spec:
  steps:
  - name: echo
    image: ubuntu
    imagePullPolicy: IfNotPresent
    command: 
    - echo
    args:
    - "Hello Tekton Task !"
