apiVersion: v1
kind: Secret
metadata:
  name: mysql-login-credentials
data:
  username:  cm9vdA==
  password:  cm9vdEAxMjM=
---

apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: task-with-secrets
spec:
  steps:
  - image: ubuntu
    imagePullPolicy: IfNotPresent
    script: |
      #!/usr/bin/env bash
      ls -ltRa /tmp/secrets
      print '\n'
      cat /tmp/secrets/user
      print '\n'
      cat /tmp/secrets/password
    volumeMounts:
    - name: login-credentials
      mountPath: /tmp/secrets
  volumes:
  - name: login-credentials
    secret:
      secretName: mysql-login-credentials


